version: '3.5'

services:

  #nome do servico
  controle-tarefas-laravel:

    #construido a partir de uma imagem customizada em ./image
    image: controle-tarefas-laravel
    
    #nome do conteiner
    container_name: controle-tarefas-laravel

    #pastas compartilhadas
    volumes:
      #pasta do codigo fonte da aplicacao
      - "./app:/root/app"

    #porta a ser exposta
    ports:
      - 8080:8080
  
    #artifício para manter o container aberto
    tty: true
